name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Github Actions from https://github.com/jamesgeorge007/github-activity-readme - Keep failing

# name: Update README

# on:
#   schedule:
#     - cron: "0 */5 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: Update this repo's README with recent activity

#     steps:
#       - uses: actions/checkout@v2
#       - uses: jamesgeorge007/github-activity-readme@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
